---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-pod"
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.container.labels }}
spec:
  containers:
    - name: {{ .Values.container.name }}
      image: {{ .Values.container.image }}
  restartPolicy: {{ .Values.container.restart }}
